### ISSUE TITLE
#10 Create architecture diagram. 

### ISSUE THREAD

**Issue by abirshah** [AdrienKamran/SOEN-341_Totally_Not_Instagram#32]
For sprint#3,We need to create an architecture diagram for our project.

**Comment by AdrienKamran** [comment]
![TNI_MTV_040320](https://user-images.githubusercontent.com/50927558/75848798-2a63ce80-5db1-11ea-873b-2dd5102d6338.PNG)

I have created the diagram using Draw.io

The raw PNG file has also been included as a file in the repository, currently under my branch.
